"""add_webhook_gpg_to_apikeys

Revision ID: 4a6dc61d39f1
Revises: 2604a7be45e9
Create Date: 2026-02-12 17:12:15.936418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a6dc61d39f1'
down_revision: Union[str, None] = '2604a7be45e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('webhook_url', sa.String(length=255), nullable=True))
    op.add_column('api_keys', sa.Column('gpg_public_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'gpg_public_key')
    op.drop_column('api_keys', 'webhook_url')
    # ### end Alembic commands ###
