name: ci-release-publish

on:
    release:
        types:
            - published

jobs:
    pypi-publish:
        name: "[Deploy] Build and upload release to PyPI"
        runs-on: ubuntu-latest
        environment: pypi
        permissions:
            id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
            contents: read
        steps:
            - name: "[Setup] Checkout repository"
              uses: actions/checkout@v6

            - name: "[Misc] Set up Python"
              uses: actions/setup-python@v6
              with:
                  python-version: "3.11"

            - name: "[Setup] Install Poetry"
              run: pipx install poetry

            - name: "[Build] Build project"
              run: poetry build

            - name: "[Deploy] Publish to PyPI"
              uses: pypa/gh-action-pypi-publish@release/v1
